apiVersion: v1
kind: ResourceQuota
metadata:
  name: ml-team-quota
  namespace: ml-team
  labels:
    team: ml-team
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "32"
    limits.memory: 64Gi
    pods: "50"
    services: "20"
    persistentvolumeclaims: "30"
    requests.storage: 200Gi
