apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform infrastructure components
  sourceRepos:
    - https://github.com/justgithubaccount/app-poly-gitops-k8s.git
    - https://charts.jetstack.io
    - https://kubernetes.github.io/ingress-nginx
    - https://grafana.github.io/helm-charts
    - https://helm.vector.dev
    - https://charts.longhorn.io
    - https://bitnami-labs.github.io/sealed-secrets
    - https://emberstack.github.io/helm-charts
    - https://charts.external-secrets.io
    - https://kubernetes-sigs.github.io/external-dns
    - https://argoproj.github.io/argo-helm
    - https://helm.openwebui.com
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
