apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenants
  namespace: argocd
spec:
  description: Tenant applications
  sourceRepos:
    - https://github.com/justgithubaccount/app-poly-gitops-k8s.git
    - https://github.com/justgithubaccount/app-poly-gitops-helm.git
  destinations:
    - namespace: chat-api
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
