apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: chat-db-cnpg
  namespace: chat-api
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instances: 1

  postgresql:
    parameters:
      shared_buffers: "256MB"
      effective_cache_size: "512MB"

  storage:
    storageClass: longhorn
    size: 5Gi

  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1"

  bootstrap:
    initdb:
      database: chat
      owner: chatapi
