---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chat-openrouter
  namespace: chat-api
spec:
  encryptedData:
    OPENROUTER_API_KEY: AgCBF3O7Rt1fHAOnyKfm1PGGKQGiYI7UCHCj8YjzXJV7qN0IpGhc+W8vPuOsOFZqEWzBYpNxcpcVvMqQNsRc8kL0DaNKpn+XcAkaypxBpIjuJoaYay+rO0+plSgQTRAIfwrGe7rfSKiytU2TrMyofE2iGXuMD59X7reHrwq+RIlKrLKG49R6SN9qu0lI8VmD/QvvZ51aD/G6YTBM2vXbe5PfRMmPETXdWfTeAm1CRgwZAqb1XqNnnHB0ylyYUMAIKOJq8CsmxleXY43+h1WZGgl1ULAUT4J53gJA8dg32zBjqAWkbufD84cl77n3JNhOvRmwbxlEq3Qc/M8QdY1O1seL5sCGaXSlDB3k0EXbxTqW9STXYsXMTkG9GetWyUQQgY2wzlsNVr1G+FVFUeeiIprJAgXH+RGqQHa/0Z0RTCwM1xlIeeZxrtwBOz0FEH2SWdxvbEQdZKU6AwkcNmezcsOruWFl2n8PjiY3Vj0ESu5oPYNBQlHFyg1hrmT3D59rpbdek2XWPH33ScK15tta/NYbdRDAzOl861H3fg3bqVKES0AieHAeA9ZXNyzV2pgSZY8M+9sxd4ixM2y0b74xJC8mZNOleZKeu1dc4/Suubwnn9gE/X2DZ3Rnt8X5k9CRAxwvi52TdqTWjLgC0npZKaGsBARtjadAv39wQkEsz0cfQvl5g+/fInHKyDF3+yEeo8eKWlmT3YzcLepHsgqGFGzNXz9ca7NsmbXxLHzS17WUPoB2KKZ+wpeagv4x/8qdrmOz0ZAZ/bBxtSYP5L8cNC+lgcgV0JfMvJwP
  template:
    metadata:
      name: chat-openrouter
      namespace: chat-api
