apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: chat-db
  namespace: chat-api
spec:
  postgresVersion: 16

  instances:
    - name: instance1
      replicas: 1
      dataVolumeClaimSpec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: "500m"
          memory: 1Gi

  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi

  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_connections: "150"
          shared_buffers: "512MB"
          effective_cache_size: "1536MB"
          maintenance_work_mem: "128MB"
          checkpoint_completion_target: "0.9"
          wal_buffers: "16MB"
          default_statistics_target: "100"
          random_page_cost: "1.1"
          effective_io_concurrency: "200"
          work_mem: "3495kB"
          min_wal_size: "1GB"
          max_wal_size: "4GB"
          max_worker_processes: "2"
          max_parallel_workers_per_gather: "1"
          max_parallel_workers: "2"
          max_parallel_maintenance_workers: "1"

  users:
    - name: chatapi
      databases:
        - chat
