apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: chat-db
  namespace: chat-api
spec:
  postgresVersion: 16

  instances:
    - name: instance1
      replicas: 1
      dataVolumeClaimSpec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: "250m"
          memory: 512Mi

  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 2Gi

  users:
    - name: chatapi
      databases:
        - chat
