apiVersion: v1
kind: ResourceQuota
metadata:
  name: data-team-quota
  namespace: data-team
  labels:
    team: data-team
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "30"
    services: "15"
    persistentvolumeclaims: "20"
    requests.storage: 100Gi
