apiVersion: v1
kind: ResourceQuota
metadata:
  name: product-team-quota
  namespace: chat-api
  labels:
    team: product-team
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "10"
    requests.storage: 50Gi
